hellomake: game_player.cpp game_server.cpp
	g++ game_player.cpp sockets.cpp fatal_error.cpp -o game_player -g -std=c++11 -pedantic -lpthread -lsfml-graphics -lsfml-window -lsfml-system
	g++ game_server.cpp sockets.cpp fatal_error.cpp -o game_server -g -std=c++11 -pedantic -lpthread -Wall